"""upd block,relation

Revision ID: 01781a2cd1a0
Revises: 2cd1b8b33501
Create Date: 2025-08-18 20:43:19.894450

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01781a2cd1a0'
down_revision: Union[str, Sequence[str], None] = '2cd1b8b33501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['relations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('blocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('blocks', 'storage',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('blocks', 'resolver',
               existing_type=postgresql.ENUM('image', 'text', 'json', name='resolver_type'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('blocks', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('blocks', 'embedding')
    op.alter_column('extensions', 'version',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('relations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('relations', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('relations', 'embedding')
    op.alter_column('storages', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('storages', 'nickname',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storages', 'nickname',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('storages', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('relations', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True))
    op.alter_column('relations', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('relations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('extensions', 'version',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.add_column('blocks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True))
    op.alter_column('blocks', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('blocks', 'resolver',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('image', 'text', 'json', name='resolver_type'),
               existing_nullable=False)
    op.alter_column('blocks', 'storage',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('blocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('relation_embeddings')
    op.drop_table('block_embeddings')
    # ### end Alembic commands ###
