"""add source.collect_at

Revision ID: 23257a559f94
Revises: b6d0898ba462
Create Date: 2025-08-20 16:37:17.387563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23257a559f94'
down_revision: Union[str, Sequence[str], None] = 'b6d0898ba462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('collect_at', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'collect_at')
    # ### end Alembic commands ###
