"""update ext

Revision ID: 2cd1b8b33501
Revises: 5f6235e23ba3
Create Date: 2025-08-18 11:07:17.663709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd1b8b33501'
down_revision: Union[str, Sequence[str], None] = '5f6235e23ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extensions', sa.Column('version', sa.String(length=64), nullable=False))
    op.add_column('extensions', sa.Column('disabled', sa.Boolean(), nullable=False, default=False))
    op.add_column('extensions', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('extensions', sa.Column('state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extensions', 'state')
    op.drop_column('extensions', 'config')
    op.drop_column('extensions', 'disabled')
    op.drop_column('extensions', 'version')
    # ### end Alembic commands ###
