"""1

Revision ID: 5f6235e23ba3
Revises: 02e59d888a38
Create Date: 2025-08-18 01:08:45.995975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6235e23ba3'
down_revision: Union[str, Sequence[str], None] = '02e59d888a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
