"""upd source

Revision ID: 751b1701b7e0
Revises: b6c0f730d897
Create Date: 2025-08-19 13:49:11.356425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751b1701b7e0'
down_revision: Union[str, Sequence[str], None] = 'b6c0f730d897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('type', sa.Text(), nullable=True))
    op.alter_column('sources', 'id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    autoincrement=True,
                    postgresql_using="id::integer"
                )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=False)
    op.drop_column('sources', 'type')
    # ### end Alembic commands ###
