"""relation cascade to block

Revision ID: b6d0898ba462
Revises: 751b1701b7e0
Create Date: 2025-08-20 13:58:47.469503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d0898ba462'
down_revision: Union[str, Sequence[str], None] = '751b1701b7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relations', 'from_',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('relations', 'to_',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('relations_from__fkey'), 'relations', type_='foreignkey')
    op.drop_constraint(op.f('relations_to__fkey'), 'relations', type_='foreignkey')
    op.create_foreign_key(None, 'relations', 'blocks', ['from_'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'relations', 'blocks', ['to_'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # 删除主键约束
    op.execute("ALTER TABLE sources DROP CONSTRAINT sources_pkey;")
    # 将 id 列设置为自增
    op.execute("ALTER TABLE sources ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;")
    # 重新添加主键约束
    op.execute("ALTER TABLE sources ADD CONSTRAINT sources_pkey PRIMARY KEY (id);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.create_foreign_key(op.f('relations_to__fkey'), 'relations', 'blocks', ['to_'], ['id'])
    op.create_foreign_key(op.f('relations_from__fkey'), 'relations', 'blocks', ['from_'], ['id'])
    op.alter_column('relations', 'to_',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('relations', 'from_',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
